apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- 10.10.10.93                             # HA-Proxy IP
controlPlaneEndpoint: "10.10.10.93:6443"   # HA-Proxy IP
etcd:
  external:
    endpoints:
    - https://10.10.10.90:2379              # Master -1 IP
    - https://10.10.10.91:2379              # Master -2 IP
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 10.30.0.0/24        # Make sure you are using different Range don't use VMs range ip, don't use 10.10.10.x range, beacese                                    # that range we already use for our 4 nodes. If you use same range it might failed when you are                                          # configuring overlay network.
apiServerExtraArgs:
  apiserver-count: "2"            # if you are using 3 master and 3 slave then increase count, and replace 2 with 3.
